- .travis.yml
> [FIX] Issue #7: fixed typos in .travis.yml

- .travis.yml
I run travis encrypt, changes are the output of this command
> [fix] The secure of Heroku

- components/exams/examsService.js
- components/exams/routes.js
- components/orders/ordersService.js
- components/orders/routes.js
- config/index.js
- package.json
- src/index.js
- utils/schema/README.md
- utils/schema/examsSchema.js
- utils/schema/ordersSchema.js
> Feat exams

- components/exams/routes.js
- components/orders/routes.js
- package.json
Update exams/routes.js
- add passport and jwt authentication
Update orders/routes.js
- add passport and jwt authentication
Refs #28
> fix(orders,exams): add passport athenticate for order and exams routes

- lib/mongo.js
Update lib/mongo.js
- create: add auto createdAt and updatedAt
- update: add auto updatedAt
Refs #48
> refactor(mongoDB): add auto createdAt and updatedAt

- utils/middleware/errorHandler.js
Update errorHandler.js
Refs #52
> refactor: error handler use Sentry only in production

- lib/password.js
- package.json
Add lib/password
- Add class PasswordGenerator
Refs #50
> feat(auth): create password lib

- package.json
> fix(version): upgrade version

- package-lock.json
- package.json
upgrade @hyfi06/html2pdf to version 1.2.0
> fix: upgrade @hyfi06/html2pdf

- components/pdfs/README.md
- components/pdfs/pdfsService.js
- components/pdfs/routes.js
Add validation in pdf route
Add documentation of pdf route
> Feat pdf validation

- components/pdfs/pdfsService.js
> fix(pdf): fix repeat results in pdf

- components/users/usersService.js
I changed filter to: $and in getUsers route for filter information
> Fix conditional on get users route

- config/index.js
> fix(auth): fix default path for patients

- components/orders/README.md
- components/orders/ordersService.js
- components/orders/routes.js
> fix(orders): user friendly message for orders endpoints

- README.md
- components/pdfs/README.md
> fix(pdf): documentation correction

- lib/asyncThrows.js
- test/auth.routes.test.js
- test/exams.routes.test.js
- test/exams.service.test.js
- utils/mocks/auth.js
- utils/mocks/config.js
- utils/mocks/exams.js
- utils/mocks/login.js
- utils/mocks/mongoLib.js
Test of exams routes and service
> Test exams

- components/orders/README.md
- components/orders/ordersService.js
- components/orders/routes.js
> refactor(orders): add isComplete query

- utils/mocks/users.js
> fix(test): fix userServiceMock. add copy function for delete in auth

- components/pdfs/routes.js
> fix(pdf): change pdf endpoint from get to post

- components/orders/routes.js
- components/results/routes.js
- test/orders.routes.test.js
- test/orders.service.test.js
- test/results.routes.test.js
- utils/mocks/messages.js
> feat(messages): create messages on order created and results created

- test/messages.routes.test.js
- test/messages.services.test.js
- utils/mocks/messages.js
- utils/mocks/mongoLib.js
> test(messeages): add test of messages routes and services

- components/orders/ordersService.js
- components/users/routes.js
> fix(users,ordes): update the response messages

- README.md
- contributing.md
Add logo HALAH readme
Add contribuding.md
Add authors
> docs: Add logo in readme, add contribuding.md add authors

- LICENSE
- README.md
> fix: add all authors in license
